# GitHub-supported funding platforms and custom destinations.
github: mithudso
patreon: mithudso
buy_me_a_coffee: mitchphudsi
custom:
  - "https://venmo.com/Mitchphudson"
  - "https://www.paypal.com/ncp/payment/8WLQPBK6PHFX2"
